import { createServer } from "node:http";
import { readFile, writeFile } from "node:fs/promises";
import { extname, join } from "node:path";

const env=Object.fromEntries((await readFile(".env","utf8")).split("\n").filter(Boolean).map(x=>x.split("=")));
const key=env.HELIUS_API_KEY,program="CLAY4M7BDfzpaTeuizZgyVw16fE7qiQhPywQzSsGLV3z",epics={"Zombie Ghost Gang":171,"Dactyl Flight Squadron":101,"Captain Flea and the Cursed Hat":147};
if(!key)throw Error("Set HELIUS_API_KEY in .env");
const rpc=`https://mainnet.helius-rpc.com/?api-key=${key}`,wsUrl=`wss://mainnet.helius-rpc.com/?api-key=${key}`;
let state=JSON.parse(await readFile("public/global-state.json","utf8"));
async function call(method,params){const r=await fetch(rpc,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:1,method,params})}),x=await r.json();if(x.error)throw Error(x.error.message);return x.result}
async function save(){state.updatedAt=new Date().toISOString();await writeFile("public/global-state.json",JSON.stringify(state,null,2)+"\n")}
async function reveal(signature){const t=await call("getTransaction",[signature,{encoding:"jsonParsed",maxSupportedTransactionVersion:0}]);if(!t?.meta?.logMessages?.some(x=>x.includes("Instruction: Reveal")))return;const asset=t.transaction.message.accountKeys[2]?.pubkey,a=await call("getAccountInfo",[asset,{encoding:"base64"}]),text=Buffer.from(a?.value?.data?.[0]||"","base64").toString("utf8"),name=Object.keys(epics).find(x=>text.includes(x));if(name){state.epicHistory=[{name,time:t.blockTime,signature,emptyPacks:state.packsSinceLastEpic||0},...(state.epicHistory||[])].slice(0,100);state.lastEpic={name,time:t.blockTime,signature};state.packsSinceLastEpic=0}else state.packsSinceLastEpic=(state.packsSinceLastEpic||0)+1;const base=Object.values(epics).reduce((s,d)=>s+1/d,0),m=state.packsSinceLastEpic+1,o=(base/(1-base))*m;state.nextEpicProbability=o/(1+o);state.individual=Object.fromEntries(Object.entries(epics).map(([n,d])=>[n,state.nextEpicProbability*((1/d)/base)]));await save();console.log(name?`Epic: ${name}`:`Reveal: ${signature}`)}
function connect(){const ws=new WebSocket(wsUrl);ws.addEventListener("open",()=>ws.send(JSON.stringify({jsonrpc:"2.0",id:1,method:"logsSubscribe",params:[{mentions:[program]},{commitment:"confirmed"}]})));ws.addEventListener("message",async({data})=>{try{const x=JSON.parse(data);const sig=x?.params?.result?.value?.signature;if(sig)await reveal(sig)}catch(e){console.error("Reveal processing error:",e.message)}});ws.addEventListener("close",()=>setTimeout(connect,2000));ws.addEventListener("error",()=>ws.close())}connect();
const types={".html":"text/html",".js":"text/javascript",".css":"text/css",".json":"application/json",".png":"image/png",".svg":"image/svg+xml"};
createServer(async(req,res)=>{if(req.url==="/api/global-state"){res.writeHead(200,{"content-type":"application/json","cache-control":"no-store"});return res.end(JSON.stringify(state))}const path=join("dist",req.url==="/"?"index.html":req.url.split("?")[0]);try{const data=await readFile(path);res.writeHead(200,{"content-type":types[extname(path)]||"application/octet-stream"});res.end(data)}catch{res.writeHead(404);res.end("Not found")}}).listen(Number(env.PORT||3000),()=>console.log(`Epic Radar running at http://localhost:${env.PORT||3000}`));
